services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: growthacy
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - "./db-data:/var/lib/mysql"